require('./convertCatcherModel');
require('./convertDrinkModel');
require('./convertEqpAmplr');
require('./convertEquipModel');
require('./convertExpModel');
require('./convertMaterialModel');
require('./convertPetModel');
require('./convertQuestModel');
require('./convertSkillModel');
