/*
 * EquipIdsByLvRank.ts
 * 数据列表，从document中转义而来
 * luleyan
 */
  
export const equipIdsByLvRank = [
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [
        [
            'DuanJian',
            'TieZhiYuGan',
            'JingLingMoZhang'
        ],
        [
            'ChangRenJian',
            'JingZhiYuGan',
            'YuHuaMoZhang'
        ]
    ],
    [
        [
            'WanDao'
        ],
        [
            'HongYingDao'
        ]
    ],
    [
        [
            'ZhongChui',
            'BanShou'
        ],
        [
            'ChaiLangZhanChui',
            'WanNengBanShou'
        ]
    ],
    [
        [
            'LieGong',
            'MoFaJian'
        ],
        [
            'QingXingLieGong',
            'FuWenJian'
        ],
        [
            'JianXiaoLieGong',
            'AoFaChangJian'
        ]
    ],
    [
        [
            'MiNiDianHuoQi',
            'DaLüBangZi'
        ],
        [
            'JiSuDianHuoQi',
            'PoSuiDeLüBangZi'
        ],
        [
            'DiJingDianHuoQi',
            'HunRanLüBangZi'
        ]
    ],
    [
        [
            'MoShiBiShou',
            'DuanJiFu',
            'HuanYuZhiJing',
            'WuShiZhangZhang',
            'TieQuanShouTao'
        ],
        [
            'ShuiJingBiShou',
            'SuiLieFu',
            'QingShanZhiJing',
            'YuYanShiZhangZhang',
            'QiangJiShouTao'
        ]
    ],
    [
        [
            'DaChiLun',
            'MaiChongFaSheQi',
            'DianXingGun'
        ],
        [
            'ZhongXingChiLun',
            'MaiChongPao',
            'GaoYaDianQiang'
        ]
    ],
    [
        [
            'PouYuDao',
            'FengShuShuZhi',
            'TuLuXiaoDao'
        ],
        [
            'FeiYuCha',
            'FengLingQuanZhang',
            'BaoPiRen'
        ]
    ],
    [
        [
            'DaiJianDeTieBang',
            'DanShouNu'
        ],
        [
            'MangCiTieBang',
            'XunJieLianNu'
        ]
    ],
    [
        [
            'TieShan',
            'FenChaFu',
            'HeFengShouZhang'
        ],
        [
            'YuHunShan',
            'XingGuangZhanFu',
            'YuFengFaZhang'
        ],
        [
            'LiMingZhiRen'
        ]
    ],
    [
        [
            'GuoLuJiaoBanQi',
            'HuoYanPenSheQi',
            'DuYinHuoQiang'
        ],
        [
            'XuanFengQi',
            'RongNengQiang',
            'ShanGuangBuQiang'
        ],
        [
            'ShuiJingZhiDanQi'
        ]
    ],
    [
        [
            'FaMuFu',
            'ShiHuaJingGu',
            'TengBian',
            'JianDingZhiJian'
        ],
        [
            'KaiShanFu',
            'GuShouJingGu',
            'JingJiCi',
            'YongQiZhiJian'
        ],
        [
            'ShenShouJingGu',
            'WangZheZhiJian'
        ]
    ],
    [
        [
            'LieDanZhiHu'
        ],
        [
            'ZhiMingZhiHu'
        ]
    ],
    [
        [
            'JiSiFaZhang',
            'MoLiDuanGong',
            'ZhanDouWaiYi'
        ],
        [
            'DiYuFaZhang',
            'MoLongDuanGong',
            'ZhuJiangWaiYi'
        ],
        [
            'MoLongSiYaoZhiGong'
        ]
    ],
    [
        [
            'KunLunShan',
            'ZhiBingQi',
            'DianCiJian',
            'SuiShiChui',
            'BaoLieDuanQiang',
            'JingZhunChangGong',
            'ZhenZhuQuanZhang',
            'QingXingSuoJia',
            'BoNengHuZhao',
            'FaShuPiFeng',
            'SenLinXiongJia'
        ],
        [
            'XuWuShan',
            'HanShuangFaSheQiang',
            'ChongNengDianCiJian',
            'FengShaZhanChui',
            'ShaYingDuanQiang',
            'YingYanChangGong',
            'ShanHuQuanZhang',
            'TieXinLianJia',
            'LiZiHuZhao',
            'PoMoPiFeng',
            'JingJiZhiJia'
        ]
    ],
    [
        [
            'TiGuDao',
            'GuoYeDeKaoYangTui',
            'TongZhiHuXiong'
        ],
        [
            'XiuRouDao',
            'QuNianDeKaoYangTui',
            'GangZhiXiongJia'
        ]
    ],
    [
        [
            'XiaoYuanDun'
        ],
        [
            'JingBingYuanDun'
        ]
    ],
    [
        [
            'FeiCuiChangDi',
            'YeSeChangQiang',
            'ZhongJinShuJuJian',
            'CanFengSan',
            'HaiDaoDeZhuaGou',
            'ChiHouWaiTao'
        ],
        [
            'ShengYuChangDi',
            'YueYingChangQiang',
            'XuanTieJuJian',
            'BiYueSan',
            'HaiDaoJiaTui',
            'MiCaiFu'
        ],
        [
            'YueShenChangQiang',
            'ShouHuZheJuJian'
        ]
    ],
    [
        [
            'MiNiFeiDanCang',
            'JiXieDao',
            'GaoSuZuanTou',
            'QiBingDingJia'
        ],
        [
            'MiNiHuoShenPao',
            'ZhanJiDao',
            'GuangSuZuanTou',
            'ShouHuZheWaiTao'
        ],
        [
            'PoJiDao'
        ]
    ],
    [
        [
            'YingHuoZhiZhang',
            'LieHuZhao',
            'DuanYa',
            'GangTieZhuangJia',
            'YouMingHuJia',
            'ShiGuiDun'
        ],
        [
            'XingZhiZhang',
            'FeiLongGou',
            'EQuanDeDuanYa',
            'JieNengZhuangJia',
            'MengYanHuJia',
            'ShiGuiHuJia'
        ],
        [
            'GuLangDeDuanYa'
        ]
    ],
    [
        [
            'YuanSeTiDao',
            'ShengChui',
            'FuYaoSan',
            'BaoJunBanJia'
        ],
        [
            'HuoYuanTiDao',
            'QiShiZhiChui',
            'XiaoYaoSan',
            'BaZhuBanJia'
        ]
    ],
    [
        [
            'EHunChangMao',
            'ShiSengJianDao',
            'XueZheChangPao'
        ],
        [
            'NiuQuZhiMao',
            'ShiXiangGuiZhiYa',
            'ShangGuFaPao'
        ]
    ],
    [
        [
            'ZhengQiTieQuan',
            'ShiSeBian',
            'HeiTieFangDun'
        ],
        [
            'JiXieTieQuan',
            'YuSheBian',
            'XueSeFangDun'
        ],
        [
            'ZhiNengTieQuan',
            'QingLongBian'
        ]
    ],
    [
        [
            'GeLanZhiRen',
            'JiXieHuiXuanBiao',
            'MoFaLaZhu',
            'JuLiZhuangJia',
            'JingShenChangPao',
            'LieBaoHuJia',
            'ZhanDouZhiHuan',
            'FaTiaoYinJi',
            'JingLingHuFu',
            'GangYuZhiJie'
        ],
        [
            'QingTianZhiRen',
            'YinSuHuiXuanBiao',
            'ShenShengLaZhu',
            'FuSheZhuangJia',
            'RuiZhiChangPao',
            'XiongShiHuJia',
            'YongQiZhiHuan',
            'ChiLunYinJi',
            'XinLingHuFu',
            'HongBaoShiZhiJie'
        ],
        [
            'BuFengTuDao',
            'GuangSuHuiXuanBiao',
            'BuMieZhiZhu',
            'CaiGuangZhuangJia',
            'XianZhiChangPao',
            'XunMengLongHuJia'
        ]
    ],
    [
        [
            'BingZhiJian',
            'YingHuaZhanChui',
            'ShiZheDunPai'
        ],
        [
            'XueNüZhiJian',
            'YeZhuZhanChui',
            'WangHunZhiDun'
        ],
        [
            'LeiJingZhiXiRen',
            'KuangZhanChui',
            'HuiMieZhiDun'
        ]
    ],
    [
        [
            'ShouZhaoBiShou',
            'HeiTieHuoQiang',
            'ShiZiGao',
            'ZuoZhanDouPeng',
            'ZhiZunXiangLian',
            'DianZiShouHuan',
            'ShouRenBiZhang',
            'CongLinHuFu'
        ],
        [
            'TuHuBiShou',
            'AnLuHuoQiang',
            'ZhongXingShiZiGao',
            'DaShiPiFeng',
            'WanMeiXiangLian',
            'ZhiNengShouHuan',
            'LongXinBiZhang',
            'ZiRanZhiYuHuFu'
        ],
        [
            'TuLongBiShou',
            'MoYanFaSheQi',
            'JingGongShiZiGao',
            'YingXiongPiFeng'
        ]
    ],
    [
        [
            'JuXingLianDao',
            'YuFengShan',
            'HuaLiZhanJia'
        ],
        [
            'WangZheLianDao',
            'LiuYunShan',
            'ShuiYinZhanJia'
        ],
        [
            'SiGeLianDao',
            'TianLingShan',
            'WeiGuangZhanJia'
        ]
    ],
    [
        [
            'DianDongHanQiang',
            'ShouChiHuoPao',
            'YongBingJian',
            'MoDaoJieZhang',
            'YingRenZhiZhao',
            'JuRenZhanFu',
            'QiDongDunPai',
            'GuLingFaPao',
            'FuMuTuTeng',
            'HeiYaoShiZhiHuan',
            'LingNengWanBiao',
            'YuYiHuiZhang',
            'ChunYinDiaoZhui'
        ],
        [
            'DiJingHanQiang',
            'AiRenShouChiPao',
            'GuiZuPeiJian',
            'YuanSuJieZhang',
            'YingRenYuMaoCi',
            'DaDiZhanFu',
            'DianZiDunPai',
            'BaoZangFaPao',
            'ShengMingTuTeng',
            'CuiHuoZhiHuan',
            'HeiShiWanBiao',
            'TianQiongHuiZhang',
            'ChaoXiDiaoZhui'
        ],
        [
            'BeiErHanQiang',
            'JiaLinShouChiPao',
            'BaoShiZhiJian',
            'TiaoHeJieZhang',
            'YingRenFengYiZhen',
            'ShanLingYiZhiZhanFu',
            'KeJiDunPai',
            'YongShengFaPao',
            'ChongShengTuTeng',
            'RanJinZhiJie',
            'LeiDaWanBiao',
            'LieKongHuiZhang',
            'XuanWoZhiLiDiaoZhui'
        ]
    ]
];
